CV-1426: allow uploading successfully downloaded blobs - and rerun job for remaining blobs

diff --git a/azure-pipeline-templates/templates/blob-sync-steps.yml b/azure-pipeline-templates/templates/blob-sync-steps.yml
--- a/azure-pipeline-templates/templates/blob-sync-steps.yml
+++ b/azure-pipeline-templates/templates/blob-sync-steps.yml
@@ -57,7 +57,7 @@ steps:
       scriptType: bash
       scriptLocation: inlineScript
       inlineScript: |
-        set -ex
+        exit-code=0
         while read blob; do
           az storage blob download-batch \
             --account-name $ACCOUNT \
@@ -65,7 +65,21 @@ steps:
             --pattern $blob \
             --destination $LOCAL_DIRECTORY \
             --only-show-errors
+          exit-code=$?
+          if [ "$exit-code" -ne 0 ]; then
+              echo "Failed while downloading blob $blob"
+              echo "exit code = $exit-code"
+              break
+          else
+              echo "Downloaded blob $blob"
+          fi
         done <production_to_${{ parameters.environment }}.log
+
+        if [ "$exit-code" -ne 0 ]; then
+          num=$(find $LOCAL_DIRECTORY -type f | wc -l)
+          echo "##vso[task.logissue type=warning;]Agent ran out of memory after $num blobs - this run will upload what was downloaded - rerun this job to upload remaining blobs"
+          echo "##vso[task.complete result=SucceededWithIssues;]"
+        fi
     env:
       ACCOUNT: campaignscrcv3produks
       CONTAINER: campaign-resource-centre-v3-production
