CV-1426: update blob sync (#614)
* CV-1426: give prod service principle "Storage Blob Data Contributor" role over non prod storage containers and remove storage keys from blob sync pipeline

* CV-1426: hardcode storage container ids and set skip_service_principal_aad_check = false

* CV-1426: debug blob list failure

* CV-1426: grant prod service principle "Storage Blob Data Contributor" role over appropriate non-prod storage containers

* CV-1426: remove setting skip_service_principal_aad_check

* CV-1426: revert debugging

* CV-1426: rewrite copy command to download and upload-batch separately to use separate service connections

* CV-1426: improve dryrun mode

* CV-1426: add mkdir function

* CV-1426: use download-batch to avoid having to use mkdir with download

* CV-1426: fix download-batch destination value

* CV-1426: allow uploading successfully downloaded blobs - and rerun job for remaining blobs

* CV-1426: fix error-code var

* CV-1426: readd mkdir

* CV-1426: fix pattern input and remove redundant logging

* CV-1426: Use exit code one for warning and delete incomplete file

* CV-1426: fix sub

* CV-1426: update artifact names

* CV-1426: remove merge mistakes

diff --git a/azure-pipeline-templates/templates/blob-sync-steps.yml b/azure-pipeline-templates/templates/blob-sync-steps.yml
--- a/azure-pipeline-templates/templates/blob-sync-steps.yml
+++ b/azure-pipeline-templates/templates/blob-sync-steps.yml
@@ -3,8 +3,6 @@ parameters:
     type: string
   - name: environment
     type: string
-  - name: azureSubscription
-    type: string
   - name: containerPrefix
     type: string
     default: 'campaign-resource-centre-v3'
@@ -14,33 +12,20 @@ parameters:
 steps:
   - checkout: none
   - task: DownloadPipelineArtifact@2
-    displayName: Download production blobs
+    displayName: Download production blob list
     inputs:
       artifactName: production.log
       targetPath: $(System.DefaultWorkingDirectory)
 
-  - task: AzureKeyVault@2
-    displayName:
-    inputs:
-      azureSubscription: dct-crccms-prod
-      KeyVaultName: dct-crc-kv-app-prod-uks
-      SecretsFilter: azure-account-key
-      RunAsPreJob: false
-
   - task: AzureCLI@2
     displayName: Get ${{ parameters.environment }} diff
     inputs:
-      azureSubscription: ${{ parameters.azureSubscription }}
+      azureSubscription: dct-crccms-${{ parameters.env }}
       scriptType: bash
       scriptLocation: inlineScript
       inlineScript: |
         set -ex
-        ACCOUNT_KEY=$(az storage account keys list \
-          --account-name ${ACCOUNT} \
-          --query "[0].value" \
-          --output tsv)
         az storage blob list \
-          --account-key $ACCOUNT_KEY \
           --account-name $ACCOUNT \
           --container-name $CONTAINER \
           --num-results 50000 \
@@ -54,51 +39,74 @@ steps:
       CONTAINER: ${{ parameters.containerPrefix }}-${{ parameters.environment }}
 
   - task: PublishPipelineArtifact@1
-    displayName: Publish ${{ parameters.environment }} blobs
+    displayName: Publish ${{ parameters.environment }} blob list
     inputs:
       targetPath: ./${{ parameters.environment }}.log
-      artifactName: ${{ parameters.environment }}.log
+      artifactName: ${{ parameters.environment }}-$(System.JobAttempt).log
 
   - task: PublishPipelineArtifact@1
     displayName: Publish ${{ parameters.environment }} diff
     inputs:
       targetPath: ./production_to_${{ parameters.environment }}.log
-      artifactName: production_to_${{ parameters.environment }}.log
-
-  - bash: |
-      echo "##vso[task.logissue type=warning;]Running in dryrun mode"
-      echo "##vso[task.complete result=SucceededWithIssues;]"
-    condition: ${{ eq(parameters.dryRun, true) }}
-    displayName: Dry Run
+      artifactName: production_to_${{ parameters.environment }}-$(System.JobAttempt).log
 
   - task: AzureCLI@2
-    condition: ${{ ne(parameters.dryRun, true) }}
-    displayName: Upload ${{ parameters.environment }} diff
+    displayName: Download ${{ parameters.environment }} diff blobs from production
     inputs:
-      azureSubscription: ${{ parameters.azureSubscription }}
+      azureSubscription: dct-crccms-prod
+      scriptType: bash
+      scriptLocation: inlineScript
+      inlineScript: |
+        exitCode=0
+        mkdir -p $LOCAL_DIRECTORY
+        while read blob; do
+          az storage blob download-batch \
+            --account-name $ACCOUNT \
+            --source $CONTAINER \
+            --pattern "$blob" \
+            --destination $LOCAL_DIRECTORY \
+            --only-show-errors
+          exitCode=$?
+          if [ "$exitCode" -ne 0 ]; then
+              echo "Failed while downloading blob $blob"
+              rm -f "$LOCAL_DIRECTORY/$blob"
+              break
+          fi
+        done <production_to_${{ parameters.environment }}.log
+
+        if [ "$exitCode" -eq 1 ]; then
+          num=$(find $LOCAL_DIRECTORY -type f | wc -l)
+          echo "##vso[task.logissue type=warning;]Agent ran out of memory after $num blobs - this run will upload what was downloaded - rerun this job to upload remaining blobs"
+          echo "##vso[task.complete result=SucceededWithIssues;]"
+        fi
+    env:
+      ACCOUNT: campaignscrcv3produks
+      CONTAINER: campaign-resource-centre-v3-production
+      LOCAL_DIRECTORY: $(System.DefaultWorkingDirectory)/blobs
+
+  - bash: |
+      echo "Print arg if needed: `if [[ '${{ parameters.dryRun }}' == 'True' ]]; then printf %s '--dryrun'; fi`"
+      if [[ '${{ parameters.dryRun }}' == 'True' ]]; then
+        echo "##vso[task.logissue type=warning;]Running in dryrun mode"
+        echo "##vso[task.complete result=SucceededWithIssues;]"
+      fi
+    displayName: 'Dry Run: ${{ parameters.dryRun }}'
+
+  - task: AzureCLI@2
+    displayName: Upload diff blobs to ${{ parameters.environment }}
+    inputs:
+      azureSubscription: dct-crccms-${{ parameters.env }}
       scriptType: bash
       scriptLocation: inlineScript
       inlineScript: |
         set -ex
-        ACCOUNT_KEY=$(az storage account keys list \
-          --account-name ${ACCOUNT} \
-          --query "[0].value" \
-          --output tsv)
-        while read blob; do
-          az storage blob copy start \
-            --source-account-name $PROD_ACCOUNT \
-            --source-account-key $PROD_ACCOUNT_KEY \
-            --source-container $PROD_CONTAINER \
-            --source-blob "$blob" \
-            --account-name $ACCOUNT \
-            --account-key $ACCOUNT_KEY \
-            --destination-container $CONTAINER \
-            --destination-blob "$blob" \
-            --only-show-errors
-        done <production_to_${{ parameters.environment }}.log
+        az storage blob upload-batch \
+          --account-name $ACCOUNT \
+          --destination $CONTAINER \
+          --source $LOCAL_DIRECTORY \
+          `if [[ '${{ parameters.dryRun }}' == 'True' ]]; then printf %s '--dryrun'; fi` \
+          --only-show-errors
     env:
       ACCOUNT: campaignsstrg${{ parameters.env }}uks
       CONTAINER: ${{ parameters.containerPrefix }}-${{ parameters.environment }}
-      PROD_ACCOUNT_KEY: $(azure-account-key)
-      PROD_ACCOUNT: campaignscrcv3produks
-      PROD_CONTAINER: campaign-resource-centre-v3-production
+      LOCAL_DIRECTORY: $(System.DefaultWorkingDirectory)/blobs
